name: Build Feature Login

on:
  push:
    branches: [feature-deployment]
    paths:
      - 'features/feature-login/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/build-and-release-template.yml
    with:
      feature-path: 'src/features/feature-login'
      feature-name: 'feature-login'
    secrets: inherit