name: Build Feature Home

on:
  push:
    branches: [feature-deployment]
    paths:
      - 'features/feature-home/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/build-and-release-template.yml
    with:
      feature-path: 'src/features/feature-home'
      feature-name: 'feature-home'
    secrets: inherit