name: Build Feature Home
on:
  push:
    branches: [feature-deployment]
    paths:
      - '../../src/features/feature-home/**'

jobs:
  call-template:
    uses: ./.github/workflows/build-release-template.yml
    with:
      feature-path: 'features/feature-home'
      feature-name: 'feature-home'