name: Build App Shell

on:
  push:
    branches: [feature-deployment]
    paths:
      - 'app-shell/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/build-and-release-template.yml
    with:
      feature-path: 'src/app-shell'
      feature-name: 'app-shell'
    secrets: inherit