name: Build Feature Quick Game

on:
  push:
    branches: [feature-deployment]
    paths:
      - 'features/feature-quick-game/**'  # correct relative path
  workflow_dispatch:   # manual trigger

jobs:
  call-template:
    uses: ./.github/workflows/build-release-template.yml
    with:
      feature-path: 'features/feature-quick-game'
      feature-name: 'feature-quick-game'