name: Build Feature Quick Game

on:
  push:
    branches: [feature-deployment]
    paths:
      - 'features/feature-quick-game/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/build-and-release-template.yml
    with:
      feature-path: 'src/features/feature-quick-game'
      feature-name: 'feature-quick-game'
    secrets: inherit